/**
 * This class is generated by jOOQ
 */
package fr.free.bkake.springjooq.domain.tables;


import fr.free.bkake.springjooq.domain.Keys;
import fr.free.bkake.springjooq.domain.Public;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthorBook extends TableImpl<Record> {

    private static final long serialVersionUID = -821595650;

    /**
     * The reference instance of <code>PUBLIC.AUTHOR_BOOK</code>
     */
    public static final AuthorBook AUTHOR_BOOK = new AuthorBook();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>PUBLIC.AUTHOR_BOOK.AUTHOR_ID</code>.
     */
    public final TableField<Record, Integer> AUTHOR_ID = createField("AUTHOR_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.AUTHOR_BOOK.BOOK_ID</code>.
     */
    public final TableField<Record, Integer> BOOK_ID = createField("BOOK_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>PUBLIC.AUTHOR_BOOK</code> table reference
     */
    public AuthorBook() {
        this("AUTHOR_BOOK", null);
    }

    /**
     * Create an aliased <code>PUBLIC.AUTHOR_BOOK</code> table reference
     */
    public AuthorBook(String alias) {
        this(alias, AUTHOR_BOOK);
    }

    private AuthorBook(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private AuthorBook(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.CONSTRAINT_A;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.CONSTRAINT_A);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthorBook as(String alias) {
        return new AuthorBook(alias, this);
    }

    /**
     * Rename this table
     */
    public AuthorBook rename(String name) {
        return new AuthorBook(name, null);
    }
}
