/**
 * This class is generated by jOOQ
 */
package fr.free.bkake.springjooq.domain;


import fr.free.bkake.springjooq.domain.tables.Author;
import fr.free.bkake.springjooq.domain.tables.AuthorBook;
import fr.free.bkake.springjooq.domain.tables.Book;
import fr.free.bkake.springjooq.domain.tables.BookStore;
import fr.free.bkake.springjooq.domain.tables.BookToBookStore;
import fr.free.bkake.springjooq.domain.tables.Language;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -2027612341;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.LANGUAGE</code>.
     */
    public final Language LANGUAGE = fr.free.bkake.springjooq.domain.tables.Language.LANGUAGE;

    /**
     * The table <code>PUBLIC.AUTHOR</code>.
     */
    public final Author AUTHOR = fr.free.bkake.springjooq.domain.tables.Author.AUTHOR;

    /**
     * The table <code>PUBLIC.AUTHOR_BOOK</code>.
     */
    public final AuthorBook AUTHOR_BOOK = fr.free.bkake.springjooq.domain.tables.AuthorBook.AUTHOR_BOOK;

    /**
     * The table <code>PUBLIC.BOOK</code>.
     */
    public final Book BOOK = fr.free.bkake.springjooq.domain.tables.Book.BOOK;

    /**
     * The table <code>PUBLIC.BOOK_STORE</code>.
     */
    public final BookStore BOOK_STORE = fr.free.bkake.springjooq.domain.tables.BookStore.BOOK_STORE;

    /**
     * The table <code>PUBLIC.BOOK_TO_BOOK_STORE</code>.
     */
    public final BookToBookStore BOOK_TO_BOOK_STORE = fr.free.bkake.springjooq.domain.tables.BookToBookStore.BOOK_TO_BOOK_STORE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Language.LANGUAGE,
            Author.AUTHOR,
            AuthorBook.AUTHOR_BOOK,
            Book.BOOK,
            BookStore.BOOK_STORE,
            BookToBookStore.BOOK_TO_BOOK_STORE);
    }
}
