/**
 * This class is generated by jOOQ
 */
package fr.free.bkake.springjooq.domain;


import fr.free.bkake.springjooq.domain.tables.Author;
import fr.free.bkake.springjooq.domain.tables.AuthorBook;
import fr.free.bkake.springjooq.domain.tables.Book;
import fr.free.bkake.springjooq.domain.tables.BookStore;
import fr.free.bkake.springjooq.domain.tables.BookToBookStore;
import fr.free.bkake.springjooq.domain.tables.Language;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.LANGUAGE</code>.
     */
    public static final Language LANGUAGE = fr.free.bkake.springjooq.domain.tables.Language.LANGUAGE;

    /**
     * The table <code>PUBLIC.AUTHOR</code>.
     */
    public static final Author AUTHOR = fr.free.bkake.springjooq.domain.tables.Author.AUTHOR;

    /**
     * The table <code>PUBLIC.AUTHOR_BOOK</code>.
     */
    public static final AuthorBook AUTHOR_BOOK = fr.free.bkake.springjooq.domain.tables.AuthorBook.AUTHOR_BOOK;

    /**
     * The table <code>PUBLIC.BOOK</code>.
     */
    public static final Book BOOK = fr.free.bkake.springjooq.domain.tables.Book.BOOK;

    /**
     * The table <code>PUBLIC.BOOK_STORE</code>.
     */
    public static final BookStore BOOK_STORE = fr.free.bkake.springjooq.domain.tables.BookStore.BOOK_STORE;

    /**
     * The table <code>PUBLIC.BOOK_TO_BOOK_STORE</code>.
     */
    public static final BookToBookStore BOOK_TO_BOOK_STORE = fr.free.bkake.springjooq.domain.tables.BookToBookStore.BOOK_TO_BOOK_STORE;
}
