/**
 * This class is generated by jOOQ
 */
package fr.free.bkake.springjooq.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthorBook implements Serializable {

    private static final long serialVersionUID = 961647564;

    private Integer authorId;
    private Integer bookId;

    public AuthorBook() {}

    public AuthorBook(AuthorBook value) {
        this.authorId = value.authorId;
        this.bookId = value.bookId;
    }

    public AuthorBook(
        Integer authorId,
        Integer bookId
    ) {
        this.authorId = authorId;
        this.bookId = bookId;
    }

    public Integer getAuthorId() {
        return this.authorId;
    }

    public AuthorBook setAuthorId(Integer authorId) {
        this.authorId = authorId;
        return this;
    }

    public Integer getBookId() {
        return this.bookId;
    }

    public AuthorBook setBookId(Integer bookId) {
        this.bookId = bookId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AuthorBook (");

        sb.append(authorId);
        sb.append(", ").append(bookId);

        sb.append(")");
        return sb.toString();
    }
}
